spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: testuser
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

telegrambots:
  bots:
      username:
      token:
      path: webhook

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operationsSorter: method

    logging:
      level:
        org:
          springframework:
            web: trace
          apache: trace